[package]
name = "rust_version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obj-rs = "0.7.0"
parry3d = "0.13.0"
itertools = "0.10.5"
urdf-rs = "0.6.9"
bevy = "0.8.1"